version: "3.9"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    environment:
      - NODE_ENV=production # Set environment variable for React app

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs # Mount certs directory (for SSL)
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount custom Nginx configuration
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - react-app
    restart: always
